### ISSUE TITLE
3.8.10 only single line rendered 

### ISSUE THREAD

**Issue by jmio23** [CMB/edbrowse#100]
I am only getting 1 single line printed, for eg going to http://www.edbrowse.org, i get:

```
6475
5181
p
Or (contact) all of the developers.; Thank you.

```
bbc.co.uk/news gives a similar single line, their copyright notice 

on Arch

**Comment by eklhad** [comment]
Looks right.
If you then want to read the entire page type ,p  just as you would in ed.

Karl Dahlke
