### ISSUE TITLE
List open files?

### ISSUE THREAD

**Issue by hallyn** [CMB/edbrowse#16]
Hi,

is there currently a way, or is there a clean way to make a function, to list the open buffers?

Something like

<buffers
e1: .ebrc
e2: http://edbrowse.org
e99: .ebmarks

**Comment by eklhad** [comment]
> is there a way to list the open buffers?

There is not, but it would be cool.

Karl Dahlke

**Comment by hallyn** [comment]
Ok, thanks, maybe this is where I can get my feet wet.

**Comment by hallyn** [comment]
Awesome, tried out bfl, works great, thanks!
