### ISSUE TITLE
segfault on ctrl-d when using readline

### ISSUE THREAD

**Issue by hallyn** [CMB/edbrowse#18]
I'm at a bit of a loss here, but I can trivially reproduce this on debian
and ubuntu.  Just do

rl
ctrl-d

I'll get a segfault which according to gdb is at the
second line in:

40fca5:       e8 96 79 ff ff          callq  407640 <readline@plt>
40fcaa:       80 38 00                cmpb   $0x0,(%rax)

which really makes no sense...

**Comment by CMB** [comment]
Serge Hallyn <notifications@github.com> writes:

> I'm at a bit of a loss here, but I can trivially reproduce this on
> debian
> and ubuntu. Just do

Yeah, this was an old bug.  It was fixed several months ago, both in a
packaged version and in git.  What version are you using on Debian and
Ubuntu?

**Comment by hallyn** [comment]
Quoting Chris Brannon (notifications@github.com):
> Serge Hallyn <notifications@github.com> writes:
> 
> > I'm at a bit of a loss here, but I can trivially reproduce this on
> > debian
> > and ubuntu. Just do
> 
> Yeah, this was an old bug.  It was fixed several months ago, both in a
> packaged version and in git.  What version are you using on Debian and
> Ubuntu?

D'oh!  I'm sorry, I'm an idiot.  That's why it made no sense to me, i
was looking at the code in git, which is fixed.  The package source in
debian doesn't have your fix.

I'll raise a debian bug -  thanks :)

**Comment by CMB** [comment]
Yeah it was fixed before the 3.6.0 release, even, so their package is
way out of date.

**Comment by CMB** [comment]
If it's helpful to anyone, the commit that fixed this was:
543e667e37deae3c130d0c837c266860a7eed58f
Fixed prior to 3.6.1.
