### ISSUE TITLE
curl/curl.h: No such file or directory

### ISSUE THREAD

**Issue by maan81** [CMB/edbrowse#20]
I am getting the error -- curl/curl.h: no such file or directory.

I do not see any curl.h in the source, or repo as well.

Here is the results I had got while installing edbrowser ( in Ubuntu 14.04)

`maan@maan-Inspiron:~/Desktop/edbrowse-3.6.1/src$ make`
`cc -DEDBROWSE_ON_LINUX   -c -o main.o main.c`
`In file included from main.c:6:0:`
`eb.h:39:23: fatal error: curl/curl.h: No such file or directory`
`#include <curl/curl.h>`
 `                      ^`
`compilation terminated.`
`make: *** [main.o] Error 1`
`

**Comment by eklhad** [comment]
> I am getting the error -- no curl.h.

You may need to install certain development packages
that are not typically distributed.
I have /usr/include/curl/curl.h via libcurl-devel
Also pcre-devel mozjs24 and mozjs24-devel,
and tidy-5, see the README file for more details.

Karl Dahlke

**Comment by maan81** [comment]
Thank you and I'm sorry for the late response.

I had installed several src, and copied them into the project's folder. I haven't tested them fully yet, but it appears to be working.
