### ISSUE TITLE
Port to mozjs38

### ISSUE THREAD

**Issue by jbicha** [CMB/edbrowse#23]
Ubuntu 17.04 now includes [mozjs38](https://launchpad.net/ubuntu/+source/mozjs38) ([SpiderMonkey 38](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Releases/38)). GNOME 3.24 has been ported to it. Once [Cinnamon](url) [follows](https://github.com/linuxmint/cjs/issues/40), edbrowse will be the only thing in Ubuntu using mozjs24. Ubuntu does not like shipping multiple versions of the same library in the same Ubuntu release.

Ubuntu will probably drop mozjs24 before Ubuntu 17.10 is released in October.

Future
----------
GNOME 3.26 (to be released in September) has a goal of porting to mozjs52 (not yet released) or at least mozjs45. Ubuntu 18.04 LTS due in April 2018 will probably include GNOME 3.26 so you'll probably need to port to that version by then also.

**Comment by jbicha** [comment]
Ubuntu 17.04 has been released now.

**Comment by CMB** [comment]
Ok, so mozjs24 is still in Ubuntu 17.04, right?
Can you give us a hard deadline for when we need to move to something
else?  I read your original message, and it said mozjs 24 would probably
be removed before 17.10 is released.

**Comment by Gottox** [comment]
On VoidLinux edbrowse is the only package that depends on mozjs24. After edbrowse has moved to a newer version, we'll remove it from the repositories.

**Comment by jbicha** [comment]
@CMB I don't think it makes sense to remove mozjs24 as long as Cinnamon still needs it. On the other hand, I don't think it makes sense to keep mozjs24 in Ubuntu only for edbrowse. Cinnamon is working on switching to mozjs38 now. I recommend to have edbrowse no longer dependent on mozjs24 before the end of September.

My comment yesterday was only to let you know that Ubuntu 17.04 is available now if that was what you were waiting on to test your app with mozjs38.

**Comment by CMB** [comment]
I should probably comment on this issue to say that we're moving
to duktape for our JS engine.  The effort is ongoing, and I'll
keep you posted.

**Comment by jbicha** [comment]
Thanks for following up.

Right now, it's looking like Debian will skip mozjs38 and go straight to mozjs52 in the next 2 months more or less. Because of that, I don't think I'd keep mozjs38 in Ubuntu 17.10 (development) after that if nothing's using it.

**Comment by CMB** [comment]
Sorry for not following up on this earlier, but edbrowse 3.7.0 was released
a few days ago.  It uses duktape, so there is no longer a dependency
on spidermonkey 24.

**Comment by paulgevers** [comment]
Shouldn't this issue be closed?
