### ISSUE TITLE
ipass length too short

### ISSUE THREAD

**Issue by OParczyk** [CMB/edbrowse#59]
Late happy holidays!
I ran into a few problems while attempting to log in to my YouTube/Google-account, one of which is that my password is deemed too long, when being entered using `ipass`. I can see why password lengths >38 characters might be considered overkill, but I don't want to tell anyone to shorten their password and I don't think you should either.

Entering it using the normal `i`-command seems to work though.

**Comment by eklhad** [comment]
Ok, I'm lazy, and just changed the constant from 40 to 80, which should be enough for everyone.

An internet search finds that almost every site has some limit on password length, though it can be as long as 500.

Karl Dahlke

**Comment by OParczyk** [comment]
Thank you! That resolves the issue for me.
