### ISSUE TITLE
src/buffers.c: function twoLetter: lines 4251-4260 duplicated as 4309-4318

### ISSUE THREAD

**Issue by schragge** [CMB/edbrowse#71]
The code for commands `db#` and `db>file` got duplicated with commit  [779eed0](https://github.com/CMB/edbrowse/commit/779eed0582415988cbd3f3fb78247d95b51e2ebe#diff-375d5f0619a2c884161be15651bb41aed85a4de2015ad7b8a7b9354191adadb4).
See [here](https://github.com/CMB/edbrowse/blob/6ffadc2aff027502a77d5c4931a13d0bd357abcc/src/buffers.c#L4251-L4260) and [here](https://github.com/CMB/edbrowse/blob/6ffadc2aff027502a77d5c4931a13d0bd357abcc/src/buffers.c#L4309-L4318).

**Comment by eklhad** [comment]
Well isn't that just silly?

It's fixed.

Karl Dahlke
