### ISSUE TITLE
static build

### ISSUE THREAD

**Issue by sylware** [CMB/edbrowse#72]
Hi,

except quickjs (minimal SDK and 0 deps), libpcre and libhtmltidy (cmake?!) SDKs are somewhat "expensive".
Could we get a static build update? What would rock is a nightly static build...

Well, I started to write a shell script to by-pass edbrowse dep SDKs for glibc/linux. Hope it does not go beyond sanity before I reach edbrowse code building.

**Comment by CMB** [comment]
Yeah, I should be able to do that soon.  I also need to make this whole
static build process more regular and easy to reproduce.  Right now it
is kind of bespoke, and it changes almost each release.
I'll let you know when we have something.

**Comment by sylware** [comment]
I am writting a build script (a little bit everyday), and I forgot about readline and curl deps then in the end this script will be actually only for my custom glibc/linux distro :(

I discovered that edbrowse uses libpcre1 and not libpce2... and I built libpcre2 :( After a quick grep it seems the port should not be that hard: very few calls with very few flags. "May" try to do it.

**Comment by ryandesign** [comment]
> I discovered that edbrowse uses libpcre1 and not libpce2... and I built libpcre2 :( After a quick grep it seems the port should not be that hard: very few calls with very few flags. "May" try to do it.

For anyone else reading, I see that you did contribute the fix to have edbrowse use pcre2 instead of pcre1 in 1d9a2e966ddb5242d79e4b6e238124c4be81f6dd.

**Comment by sylware** [comment]
There is a recent static build and I have my build script short-cutting all SDKs (except readline and curl).

Closing.
