### ISSUE TITLE
GPL license version clarification

### ISSUE THREAD

**Issue by ryandesign** [CMB/edbrowse#81]
What is the license of edbrowse? Is it [GPL-1.0-only](https://spdx.org/licenses/GPL-1.0-only.html) or [GPL-1.0-or-later](https://spdx.org/licenses/GPL-1.0-or-later.html) or [GPL-2.0-only](https://spdx.org/licenses/GPL-2.0-only.html) or [GPL-2.0-or-later](https://spdx.org/licenses/GPL-2.0-or-later.html) or [GPL-3.0-only](https://spdx.org/licenses/GPL-3.0-only.html) or [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html) or perhaps even something else?

Most source files say "released under GPL" (which is ambiguous but could be reasonably interpreted to mean "any past, current, or future version of GPL") but allowance of GPL version 1 is pretty uncommon outside of perl software (which I realize edbrowse version 1 was).

Some files (win32/vsprtf.c and win32/vsprtf.h) say "Licence: GNU GPL version 2" (which one must probably interpret as "GPL version 2 only") however I am not building on Windows so I assume these files and their licenses do not apply to me (and indeed the README says "For a time, edbrowse could be built on windows, but this is no longer supported" so perhaps these files and their licenses are no longer relevant to anyone).

doc/man-edbrowse-debian.1 says "You may distribute under the terms of the GNU General Public License as specified in the file /usr/share/common-licences/GPLv2 that comes with the Debian distribution" but since that manpage was written by a third party I don't know how authoritative it is regarding the license.

**Comment by eklhad** [comment]
Clarified: gpl 2.
Now referenced only in the COPYING file, not scattered through various sourcefiles, which was kinda silly.

Karl Dahlke

**Comment by ryandesign** [comment]
Thanks for clarifying!

Where you want to indicate the license is of course up to you, but putting such notice into each source file is not necessarily silly; in fact the [instructions for how to use the GPL](https://www.gnu.org/licenses/gpl-howto.en.html) say to do so.

Note that a consequence of licensing edbrowse GPL-2.0-only is that it is not legal to distribute a binary of edbrowse that is linked with your dependency readline 6.0 or greater (which is licensed GPL-3.0-or-later). This could be an additional reason to make the use of readline optional; see #80.
