### ISSUE TITLE
Browsing urbandictionary.com with JavaScript enabled results in a segmentation fault

### ISSUE THREAD

**Issue by TheQuinbox** [CMB/edbrowse#85]
Edbrowse version: 3.8.5
Steps to reproduce:
1. Enable javaScript.
2. `b http://urbandictionary.com/`
3. Attempt to navigate around. I typed 1, then enter go go down a few lines. After trying to pass the home link, I get a segfault.

This wouldn't be a huge deal, if not for the fact that Edbrowse is unable to search on Urban Dictionary without javaScript enabled. To test this:
1. Disable JavaScript.
2. `b http://urbandictionary.com/`
3. `/<Search`
4. `i=test`
5. `i*`
6. `ft`

As you can see from the page title, the search is never performed.

**Comment by eklhad** [comment]
Well for me, using the latest (git pull), I haven't been able to 
reproduce the seg fault but I'm still playing around. 
It does work fine without js though. 
The top line looks like

{Random definitions}<>

I set i=yellow
then down two lines is <Search> and i* gives me the meaning of yellow.

Karl Dahlke

**Comment by TheQuinbox** [comment]
Oh, you're right. No idea why it didn't work without JavaScript before.

**Comment by TheQuinbox** [comment]
Am still able to reproduce the segfault, though.
```
< $ edbrowse
> edbrowse ready
< js
> javascript enabled
< b http://urbandictionary.com
> 118839
> 6363
< 1
> Frame {adreporter}
<enter
<enter
>{Random definitions}<>
< enter
> Segmentation fault
```

**Comment by eklhad** [comment]
> Am still able to reproduce the segfault, though.

Pull, and try again.

Karl Dahlke

**Comment by TheQuinbox** [comment]
All seems fixed, thanks!
