### ISSUE TITLE
r !command "Cannot open command"

### ISSUE THREAD

**Issue by pabloasanchez** [CMB/edbrowse#99]
When trying to write in the buffer from shell, I get a "cannot open _command_" message

```
r !date
cannot open !date
```

I noticed a warning in the users guide about `edbrowse` spawning `sh` even if your `$SHELL` is `bash`:

> Warning - some versions of system() spawn /bin/sh, regardless of your $SHELL environment variable. We have no control over this. Your shell command, or your plugin commands, might not work properly if you are using bash features, and edbrowse launches sh. ed has the same issue.

I checked with `!echo $RANDOM` as the guide suggests, and sure enough, I get no output.

But if I try to run the same thing in `ed` it works fine (even if it seems to spawn `sh` as well)

ed:
```
!echo $SHELL
/bin/bash
!
!echo $RANDOM

!
!/bin/bash -c 'echo $RANDOM' 
7102
!
r !date
30
%n
1	sáb 20 jul 2024 03:59:38 CST
```

So is the spawned `sh` the problem?  

In any case, how could I make this work in `edbrowse` (writing from shell)?

**Comment by eklhad** [comment]
I would guess your version of edbrowse doesn't have the r ! feature;
thus it tries to open the file !date and there is no such file.
Check with edbrowse -v
though I thought r ! was there for a while.

Karl Dahlke

**Comment by pabloasanchez** [comment]
You are right, I was using 3.7.7.
Thanks Karl!
